[package]
name = "pishpirik"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
colored = "3.0.0"
crossterm = "0.27"
rand = "0.8"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
